### ISSUE TITLE
[FEATURE] 주류 조회 api설계

### ISSUE THREAD

**Issue by SunYerim** [SunjooAI/sunjoo-server-drinktionary#4]
## 📑 작업 사항 
주류 조회에 관련된 모든 api를 작성한다.

## To-do
- [ ] 전체 주류 리스트 조회
- [ ] 개별 주류 정보 조회
- [ ] 주류 타입별 조회
- [ ] 주류 이름별 조회
