### ISSUE TITLE
[FEATURE] 주류 조회 api 작성

### ISSUE THREAD

**Issue by SunYerim** [SunjooAI/sunjoo-server-drinktionary#8]
## 📑 작업 사항 
주류 조회와 관련된 api를 작성한다.

## To-do
- [x] 주류 전체 조회
- [x] 주류 개별 조회
- [x] 주류 타입별 조회
- [x] 주류 이름별 조회
